version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3

jobs:
  test:
    environment:
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:14-jdk-buster-node

    working_directory: ~/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - mongo-spring-search-{{ checksum "pom.xml" }}
            - mongo-spring-search-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: mongo-spring-search-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean test
      - store_artifacts:
          path:  ~/project/target/coverage-reports
      - codecov/upload:
          file: ~/project/target/coverage-reports/jacoco/jacoco.xml
          flags: coverage
          upload_name: Coverage

workflows:
  version: 2
  test:
    jobs:
      - test
