version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  test:
    environment:
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:17-jdk-buster-node
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - mongo-spring-search-{{ checksum "pom.xml" }}
            - mongo-spring-search-
      - run:
          name: Download dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: mongo-spring-search-{{ checksum "pom.xml" }}
      - run:
          name: Run tests
          command: mvn clean test
      - store_artifacts:
          path: target/surefire-reports
          destination: surefire-reports
      - store_artifacts:
          path: target/coverage-reports
          destination: coverage-reports
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f target/coverage-reports/jacoco/jacoco.xml


workflows:
  version: 2
  test:
    jobs:
      - test
